{% macro define_tf_primitive(primitive_name, primitive_config, primitive_index) -%}
{% set tf=namespace(**dict(tf_primitive_default.get(primitive_name, {}).get('tf', {}).items() + primitive_config.get('tf', {}).items())) -%}
{% set var=namespace(**dict(tf_primitive_default.get(primitive_name, {}).get('var', {}).items() + primitive_config.get('var', {}).items())) -%}
{% set tag=namespace(items = dict(tf_primitive_default.get(primitive_name, {}).get('tags', {}).items() + primitive_config.get('tags', {}).items()).items()) -%}
{% set name=primitive_config.get('name', tf_primitive_default.get(primitive_name, {}).get('name', primitive_index)) -%}
{% set templates=primitive_config.get('make', tf_primitive_default.get(primitive_name, {}).get('make', [primitive_name + '/make.j2',])) -%}
{% for template in templates -%}

{% include template ignore missing with context %}

{% endfor -%}
{%- endmacro %}
{% if skip_project_name_domain_prefix == true %}
{% set domain_name = project_env_zone %}
{% else %}
{% set domain_name = project_name + "." + project_env_zone %}
{% endif %}

##### begin:header
{% include 'header.make.j2' ignore missing %}
##### end:header
{% for primitive_dict in tf_primitive -%}
{% set primitive_index = loop.index | to_json -%}
{% for primitive_name, primitive_config in primitive_dict.items() -%}
{% if primitive_config == True -%}
{% set primitive_config = {} -%}
{%- endif  %}
{% if primitive_config is not mapping  -%}
{% set primitive_config = dict(name=primitive_config) %}
{%- endif  %}
##### begin:{{ primitive_name }}:{{primitive_index}}
{{ define_tf_primitive(primitive_name, primitive_config, primitive_index) }}
##### end:{{ primitive_name }}:{{primitive_index}}
{% endfor -%}
{% endfor %}
##### begin:footer
{% include 'footer.make.j2' ignore missing %}

##### end:footer